"""Project scaffold — creates .beep.md and .beep/ tree for onboarding."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


@dataclass
class ScaffoldResult:
    created: list[str]
    skipped: list[str]


class ProjectScaffold:
    def __init__(self, workspace_root: Path) -> None:
        self._root = workspace_root

    def scaffold(self, *, force: bool = False) -> ScaffoldResult:
        created: list[str] = []
        skipped: list[str] = []

        beep_dir = self._root / ".beep"
        beep_dir.mkdir(parents=True, exist_ok=True)

        memory_file = self._root / ".beep.md"
        if self._write_if_needed(
            memory_file,
            self._build_memory(),
            force,
        ):
            created.append(str(memory_file.relative_to(self._root)))
        else:
            skipped.append(str(memory_file.relative_to(self._root)))

        rules_file = beep_dir / "rules.md"
        if self._write_if_needed(
            rules_file,
            self._build_rules(),
            force,
        ):
            created.append(str(rules_file.relative_to(self._root)))
        else:
            skipped.append(str(rules_file.relative_to(self._root)))

        ignore_file = beep_dir / "ignore"
        if self._write_if_needed(
            ignore_file,
            self._build_ignore(),
            force,
        ):
            created.append(str(ignore_file.relative_to(self._root)))
        else:
            skipped.append(str(ignore_file.relative_to(self._root)))

        commands_file = beep_dir / "commands.md"
        if self._write_if_needed(
            commands_file,
            self._build_commands(),
            force,
        ):
            created.append(str(commands_file.relative_to(self._root)))
        else:
            skipped.append(str(commands_file.relative_to(self._root)))

        return ScaffoldResult(created=created, skipped=skipped)

    def _write_if_needed(self, path: Path, content: str, force: bool) -> bool:
        if path.exists() and not force:
            return False
        path.write_text(content, encoding="utf-8")
        return True

    def _build_memory(self) -> str:
        return (
            "# Project Memory\n\n"
            "## About this project\n\n"
            "Brief description of what this project does.\n\n"
            "## Tech stack\n\n"
            "- Language: ...\n"
            "- Framework: ...\n"
            "- Database: ...\n\n"
            "## Conventions\n\n"
            "- Code style: ...\n"
            "- Testing: ...\n"
            "- Git workflow: ...\n\n"
            "[Last updated: auto-generated by `beep init`]\n"
        )

    def _build_rules(self) -> str:
        return (
            "# Project Rules\n\n"
            "Custom rules and conventions the AI assistant should follow.\n\n"
            "## Code Standards\n\n"
            "- Follow the project's established coding conventions.\n"
            "- Write tests for new functionality.\n"
            "- Keep functions focused and under 50 lines.\n\n"
            "## Review Guidelines\n\n"
            "- All changes must be reviewed before merging.\n"
            "- Check for security issues in dependency changes.\n"
        )

    def _build_ignore(self) -> str:
        return (
            "## Patterns for files/dirs to exclude from context\n"
            "node_modules/\n"
            ".venv/\n"
            "venv/\n"
            "__pycache__/\n"
            "*.pyc\n"
            ".env\n"
            "dist/\n"
            "build/\n"
            ".git/\n"
        )

    def _build_commands(self) -> str:
        return (
            "# Custom Commands\n\n"
            "Add custom slash commands for this project.\n\n"
            "## Example\n\n"
            "```\n"
            "/mycommand: description\n"
            "```\n\n"
            "See `/help` for available built-in commands.\n"
        )
