"""Structured output support for agent planning and action schemas.

Provides Pydantic models for agent planning, action declaration,
and structured response parsing to improve agent reliability.
"""

from __future__ import annotations

from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


class AgentStepType(str, Enum):
    """Type of step the agent should take."""

    READ = "read"
    ANALYZE = "analyze"
    WRITE = "write"
    EDIT = "edit"
    SHELL = "shell"
    TEST = "test"
    COMPLETE = "complete"
    ASK_CLARIFICATION = "ask_clarification"


class AgentPlanStep(BaseModel):
    """A single step in an agent plan."""

    step_number: int = Field(description="Sequential step number")
    step_type: AgentStepType = Field(description="Type of operation for this step")
    description: str = Field(description="What this step does in plain language")
    files_involved: list[str] = Field(
        default_factory=list, description="Files this step reads or modifies"
    )
    tool_name: Optional[str] = Field(default=None, description="Primary tool for this step")
    expected_outcome: Optional[str] = Field(
        default=None, description="What success looks like for this step"
    )


class AgentPlan(BaseModel):
    """A structured plan generated by the agent before execution."""

    goal: str = Field(description="The goal being addressed")
    summary: str = Field(description="Brief summary of the approach")
    steps: list[AgentPlanStep] = Field(
        description="Ordered steps to achieve the goal",
        min_items=1,
    )
    estimated_complexity: str = Field(
        default="medium",
        description="Complexity: simple, medium, complex",
    )
    risks: list[str] = Field(default_factory=list, description="Potential risks or concerns")

    class Config:
        json_schema_extra = {
            "examples": [
                {
                    "goal": "Add logging to the auth module",
                    "summary": "Add structured logging to authentication functions",
                    "steps": [
                        {
                            "step_number": 1,
                            "step_type": "read",
                            "description": "Read the current auth module",
                            "files_involved": ["src/auth.py"],
                            "tool_name": "file_read",
                        },
                        {
                            "step_number": 2,
                            "step_type": "edit",
                            "description": "Add logging imports and calls",
                            "files_involved": ["src/auth.py"],
                            "tool_name": "file_edit",
                        },
                    ],
                    "estimated_complexity": "medium",
                    "risks": ["May increase response latency slightly"],
                }
            ]
        }


class AgentAction(BaseModel):
    """A structured declaration of what the agent intends to do next."""

    action_type: AgentStepType = Field(description="Type of action")
    description: str = Field(description="Brief description of the action")
    tool_name: str = Field(description="Tool to use")
    tool_arguments: dict[str, Any] = Field(
        default_factory=dict,
        description="Arguments to pass to the tool",
    )
    reasoning: Optional[str] = Field(
        default=None,
        description="Why this action is being taken",
    )


class AgentStatus(BaseModel):
    """Structured status update from the agent."""

    phase: str = Field(
        description="Current phase: planning, executing, reviewing, done, failed",
    )
    current_step: Optional[int] = Field(default=None, description="Current step number")
    total_steps: Optional[int] = Field(default=None, description="Total planned steps")
    progress_message: str = Field(description="Human-readable progress description")
    files_modified: list[str] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)


def parse_plan_from_response(content: str) -> AgentPlan | None:
    """Try to parse an AgentPlan from a text response.

    Looks for JSON block in the response. Returns None if not found or invalid.
    """
    import json

    # Look for JSON block between ```json and ``` markers
    markers = ["```json", "```"]
    start = content.find(markers[0])
    if start == -1:
        # Try to find raw JSON
        start = content.find("{")
        if start == -1:
            return None
        end = content.rfind("}")
        if end == -1:
            return None
        json_str = content[start : end + 1]
    else:
        start += len(markers[0])
        end = content.find(markers[1], start)
        if end == -1:
            return None
        json_str = content[start:end].strip()

    try:
        data = json.loads(json_str)
        return AgentPlan.model_validate(data)
    except Exception:
        return None
